language: rust
os: linux
dist: xenial

cache:
  - cargo

rust:
  - stable

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "^0.3" mdbook)
  - cargo install-update -a

script:
  - python setEnvAndBuild.py
  - source setEnv.sh

deploy:
  - provider: pages
    strategy: git
    github-token: $GITHUB_TOKEN
    edge: true
    local-dir: src/java/book # In case of custom book path: path/to/mybook/book
    keep-history: false
    verbose: true
    repo: weisanju/note-java
    deployment_file: true
    on:
      branch: main
      condition: $java != ''
    target_branch: main

  - provider: pages
    strategy: git
    github-token: $GITHUB_TOKEN
    edge: true
    local-dir: src/python/book # In case of custom book path: path/to/mybook/book
    keep-history: false
    verbose: true
    repo: weisanju/note-python
    deployment_file: true
    on:
      branch: main
      condition: $python != ''
    target_branch: main

  - provider: pages
    strategy: git
    github-token: $GITHUB_TOKEN
    edge: true
    local-dir: src/db/book # In case of custom book path: path/to/mybook/book
    keep-history: false
    verbose: true
    repo: weisanju/note-db
    deployment_file: true
    on:
      branch: main
      condition: $db != ''
    target_branch: main
#frontend:
  - provider: pages
    strategy: git
    github-token: $GITHUB_TOKEN
    edge: true
    local-dir: src/frontend/book # In case of custom book path: path/to/mybook/book
    keep-history: false
    verbose: true
    repo: weisanju/note-front
    deployment_file: true
    on:
      branch: main
      condition: $frontend != ''
    target_branch: main

# mw:xxxx
  - provider: pages
    strategy: git
    github-token: $GITHUB_TOKEN
    edge: true
    local-dir: src/mw/book # In case of custom book path: path/to/mybook/book
    keep-history: false
    verbose: true
    repo: weisanju/mw
    deployment_file: true
    on:
      branch: main
      condition: $mw != ''
    target_branch: main
