[book]
authors = ["肖佳权"]
language = "zh_CN"
multilingual = false
src = "src"
title = "note"

[output.html.fold]
enable = true
level = 0

[output.html]
mathjax-support = true



[build]
create-missing=false